
services:
  inventory-service:
    build: ./inventory
    container_name: inventory-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "8082:8082"

  product-service:
    build: ./product
    container_name: product-service
    ports:
      - "8083:8083"

  # Optional frontend service
  client:
    build: ./client
    container_name: client-app
    ports:
      - "3000:3000"

